name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:

  build-rock:
    uses: canonical/sdcore-github-workflows/.github/workflows/build-rock.yaml@v1.0.0

  scan-rock:
    needs: build-rock
    uses: canonical/sdcore-github-workflows/.github/workflows/scan-rock.yaml@v1.0.0

  publish-rock:
    if: github.ref_name == 'main'
    needs: scan-rock
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-rock.yaml@v1.0.0
